### ISSUE TITLE
How do I pass configuration settings to the parser?

### ISSUE THREAD

**Issue by wesyah234** [peerlibrary/meteor-xml2js#11]
I would like to set explicitArray to false as documented here:
https://github.com/Leonidas-from-XIV/node-xml2js#options

explicitArray (default: true): Always put child nodes in an array if true; otherwise an array is created only if there is more than one.

How do I do that with this meteor package?

**Comment by mitar** [comment]
```
xml2js.parseStringSync(xml, {
  explicitArray: true
});
```

**Comment by wesyah234** [comment]
thank you!! :+1:
