### ISSUE TITLE
Error: Future resolved more than once

### ISSUE THREAD

**Issue by EduardoMercado** [peerlibrary/meteor-xml2js#7]
Hello

I Have been using your module for more than 6 months and now that i have updated Meteor from 1.0 to 1.0.3.1
and
peerlibrary:blocking  upgraded from 0.4.2 to 0.5.1
peerlibrary:fs        upgraded from 0.1.5 to 0.1.6
peerlibrary:xml2js    upgraded from 0.4.4_3 to 0.4.4_4

I am getting this error.
If you could take a look at it I would appreciated it.

Thanks

I20150226-01:51:32.083(-6)? Exception while invoking method 'generaFacturaVPG' Error: Future resolved more than once
I20150226-01:51:32.086(-6)?     at Object.Future.return (/Users/eduardomercado/.meteor/packages/meteor-tool/.1.0.41.19nv8s1++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:154:10)
I20150226-01:51:32.086(-6)?     at Object.<anonymous> (/Users/eduardomercado/.meteor/packages/meteor-tool/.1.0.41.19nv8s1++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:242:16)
I20150226-01:51:32.086(-6)?     at Parser.<anonymous> (/Users/eduardomercado/.meteor/packages/peerlibrary_xml2js/.0.4.4_4.1dnnp1i++os+web.browser+web.cordova/npm/node_modules/xml2js/lib/xml2js.js:384:20)
I20150226-01:51:32.087(-6)?     at Parser.emit (events.js:95:17)
I20150226-01:51:32.087(-6)?     at Object.onclosetag (/Users/eduardomercado/.meteor/packages/peerlibrary_xml2js/.0.4.4_4.1dnnp1i++os+web.browser+web.cordova/npm/node_modules/xml2js/lib/xml2js.js:348:26)
I20150226-01:51:32.087(-6)?     at emit (/Users/eduardomercado/.meteor/packages/peerlibrary_xml2js/.0.4.4_4.1dnnp1i++os+web.browser+web.cordova/npm/node_modules/xml2js/node_modules/sax/lib/sax.js:615:33)
I20150226-01:51:32.087(-6)?     at emitNode (/Users/eduardomercado/.meteor/packages/peerlibrary_xml2js/.0.4.4_4.1dnnp1i++os+web.browser+web.cordova/npm/node_modules/xml2js/node_modules/sax/lib/sax.js:620:3)
I20150226-01:51:32.087(-6)?     at closeTag (/Users/eduardomercado/.meteor/packages/peerlibrary_xml2js/.0.4.4_4.1dnnp1i++os+web.browser+web.cordova/npm/node_modules/xml2js/node_modules/sax/lib/sax.js:861:5)
I20150226-01:51:32.087(-6)?     at Object.write (/Users/eduardomercado/.meteor/packages/peerlibrary_xml2js/.0.4.4_4.1dnnp1i++os+web.browser+web.cordova/npm/node_modules/xml2js/node_modules/sax/lib/sax.js:1294:29)
I20150226-01:51:32.087(-6)?     at Parser.exports.Parser.Parser.parseString (/Users/eduardomercado/.meteor/packages/peerlibrary_xml2js/.0.4.4_4.1dnnp1i++os+web.browser+web.cordova/npm/node_modules/xml2js/lib/xml2js.js:403:31)

**Comment by EduardoMercado** [comment]
I am using the xml2js.parseStringSync function

**Comment by timbrandin** [comment]
Same issue here

**Comment by shoshi** [comment]
+1

**Comment by shoshi** [comment]
For the time being, downgrading to version 0.4.4_3 solves the problem. You can limit it in the `packages` file like this: `peerlibrary:xml2js@=0.4.4_3`

**Comment by EduardoMercado** [comment]
Just a note: It works fine if you use Meteor.wrapAsync(xml2js.parseString) instead on xml2js.parseStringSync

**Comment by mitar** [comment]
I released a bugfix version `peerlibrary:xml2js@0.4.5_1`. Thanks for reporting it.

**Comment by timbrandin** [comment]
:+1:

**Comment by EduardoMercado** [comment]
Thanks!

**Comment by shoshi** [comment]
This is working well now, thanks for the speedy resolution! ^_^

**Comment by timbrandin** [comment]
Great work!!

2015-02-27 18:39 GMT+01:00 shoshi <notifications@github.com>:

> This is working well now, thanks for the speedy resolution! ^_^
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/peerlibrary/meteor-xml2js/issues/7#issuecomment-76437720>
> .
>



-- 
Cheers,
// Tim Brandin @timbrandin <https://twitter.com/#!/timbrandin>
http://timbrandin.com
http://studiointeract.com
