### ISSUE TITLE
Mispelling on athmosphere page

### ISSUE THREAD

**Issue by kkalinowski** [peerlibrary/meteor-xml2js#8]
In the installation section there is **meteor add peerlibray:xml2js** instead of **meteor add peerlibrary:xml2js**

**Comment by mitar** [comment]
Duplicate of #6.

**Comment by mitar** [comment]
Not sure why it is still an old readme there. I published a new version with correct command in meantime.

**Comment by mitar** [comment]
@tmeasday, do you know why is there still and old README?

**Comment by mitar** [comment]
OK, publishing a new version fixed the problem. It seems I have just merged the fix in before, without really publishing it.

**Comment by mitar** [comment]
Thanks, @kkalinowski, for pointing it out.
